### ISSUE TITLE
Some queries do not have Enrichr and download links

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/signature-commons-ui#149]
This one for example:
https://amp.pharm.mssm.edu/sigcom/#/MetadataSearch?q=AGING

**Comment by jeevangelista** [comment]
Hi Avi,

It works for me:
<img width="1141" alt="Screen Shot 2019-09-07 at 9 28 02 PM" src="https://user-images.githubusercontent.com/1305807/64481993-89f07100-d1b6-11e9-972f-20fa35511145.png">

Only the signature tabs have enrichr and download links. Downloading whole library/dataset is currently deactivated. Should I put this feature back on?

**Comment by AviMaayan** [comment]
I see... This is confusing... The DATASET tab should appear on the right... and GENE tab should be removed...
