### ISSUE TITLE
Clicking on TRANSFAC results links to an empty screen

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/signature-commons-ui#183]
https://amp.pharm.mssm.edu/sigcom/#/SignatureSearch/Overlap/d7096e8c-1904-5b5c-bd87-9496ef5f756c

**Comment by jeevangelista** [comment]
Hi Avi,

Do you have the geneset list for this?

**Comment by AviMaayan** [comment]
I was hoping that the link will have the signature saved... You can try this one:
KRTDAP
GM156
OLFR1325
OLFR959
OLFR958
OLFR1323
OLFR955
LAS1L
MTHFD1
IL31RA
GM10439
L1TD1
D2ERTD750E
C3AR1
PON2
OLFR1316
GM1631
CAPNS2
2610507B11RIK
SPOCK3
SNX27
PRL3C1
GTSE1
NEURL1A
TOE1
GM6086
PLSCR2
OLFR970
PKIB
OLFR1308
JTB
PKIA
4930458L03RIK
CRYAA
SET
SVS3A
3110052M02RIK
POP4
SVS3B
PDGFB
PLA2G6
TEX28
OLFR967
GATA1
OLFR969
T
RNF219
LOH12CR1
FAM110C
OLFR961
PIP5K1A
ADAM6A
PET112L
GSTM5
SPHK1
PSG25
DCBLD1
MMP11
OLFR915
SLC7A5
