### ISSUE TITLE
namespace:value for identifiers

### ISSUE THREAD

**Issue by u8sand** [MaayanLab/signature-commons-ui#204]
Because `ns:id` is a common scheme for identifiers, we should make sure that we don't end up breaking this during search with out code which turns `key:value` into `meta.key = value`. What we should do is turn this into an OR clause to mitigate this, searching for both `ns:id` normally *AND* `meta.ns = id` in the request.

**Comment by jeevangelista** [comment]
fixed: b814a43e606a743c603200553e3f22b2f728abf1
